project:
  type: website
  output-dir: docs

website:
  favicon: /images/Metamorphosis_transparent.png
  title: "Metamorphosis Performance & Rehabilitation Training"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: services.qmd
        text: Services
      - href: frequently_asked_questions.qmd
        text: FAQ
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



