project:
  type: website
  output-dir: docs

lightbox: auto

website:
  favicon: "/images/tadpole_logo.png"
  title: "Metamorphosis Performance & Rehabilitation Training"
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: About/mission_statement.qmd
            text: Mission Statement
          - href: About/staff.qmd
            text: Staff
      - href: services.qmd
        text: Services
      - href: frequently_asked_questions.qmd
        text: FAQ
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  #typst: default



