project:
  type: website

website:
  favicon: /images/Metamorphosis_transparent.png
  title: "868-Ness-Dela Cruz-Kerstein-Yomogida-business"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



