---
title: Frequently Asked Questions (FAQs)
---


# Do you accept my insurance?

We accept Medicare, Tricare/Triwest, VA, and Auto. 
We are out-of-network with all other plans. 
Please see out [insurance page](insurance.qmd) or call for more information

# Do I need a prescription?

No. In California you can see a physical therapist without a prescription unless you are treated for more than 12 visits or 45 days

# Do I Need Exercise Equipment?

Most treatment will take place in the home, office, or a gym. Oftentimes, minimal additional equipment is needed to achieve your goals. 
In the case that you do require specific equipment for your individual treatment, it will be provided by your physical therapist.

# Where will we meet?

We can meet in your home, office, gym (if permissible), football field, track, the beach, or wherever you may need (given it is geographically feasible). 
We make our treatment location as convenient and easy to accommodate your specific needs.

# What Payment do you Accept

Cash, Credit, Check, Debit, Venmo, and Paypal.


# What Should I Wear?

Loose fitting, comfortable gym clothes and athletic shoes.


# How many sessions will I need to get better?

It depends. Every case is individual and will get a personalized treatment approach. Estimates can be made over the phone; however, a full examination will provide a more accurate prognosis. In general, patients that receive individualized 1-on-1 care tend to recover much quicker than those that do not!